services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - rustfs-data:/rustfs
    networks:
      - application_network

volumes:
  rustfs-data:

networks:
  application_network:
